# Generated by Django 5.2.1 on 2025-09-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(help_text='Upload project image (recommended size: 800x450px)', upload_to='projects/images/')),
                ('tech_stack', models.CharField(help_text='Comma-separated list of technologies (e.g., React, Node.js, MongoDB)', max_length=500)),
                ('github_url', models.URLField(blank=True, help_text='GitHub repository URL', null=True)),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube video URL (will be embedded)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured', models.BooleanField(default=False, help_text='Mark as featured project')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-featured', '-created_at'],
            },
        ),
    ]
