# Generated by Django 5.2.1 on 2025-09-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zero', '0002_remove_project_image_project_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn project/article URL', null=True),
        ),
    ]
