# Generated by Django 5.2.1 on 2025-09-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zero', '0003_project_linkedin_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image_url',
        ),
        migrations.AddField(
            model_name='project',
            name='preview_url',
            field=models.URLField(blank=True, help_text='Preview URL for the project (live demo, portfolio page, etc.)', null=True),
        ),
    ]
