# Generated by Django 5.2.1 on 2025-09-05 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zero', '0005_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(help_text='Please enter a valid email address.', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'Message must be at least 10 characters long.'), django.core.validators.MaxLengthValidator(1000, 'Message must be less than 1000 characters.')]),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Name must be at least 2 characters long.'), django.core.validators.RegexValidator(message='Name should contain only letters and spaces.', regex='^[a-zA-Z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional. Format: +1234567890', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5, 'Subject must be at least 5 characters long.'), django.core.validators.MaxLengthValidator(200, 'Subject must be less than 200 characters.')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'Description must be at least 10 characters long.')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(help_text='Comma-separated list of technologies (e.g., React, Node.js, MongoDB)', max_length=500, validators=[django.core.validators.MinLengthValidator(2, 'Please add at least one technology.')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3, 'Title must be at least 3 characters long.')]),
        ),
    ]
