# Generated by Django 5.2.1 on 2025-09-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zero', '0008_certification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='image',
        ),
        migrations.AddField(
            model_name='certification',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL for certification', null=True),
        ),
    ]
