# Generated by Django 5.2.1 on 2025-09-11 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zero', '0009_remove_certification_image_certification_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={},
        ),
        migrations.RemoveField(
            model_name='certification',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='credential_id',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='credential_url',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='description',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='issuer',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='updated_at',
        ),
    ]
