# Generated by Django 5.2.1 on 2025-09-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zero', '0010_alter_certification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_date',
            field=models.DateField(blank=True, help_text='Date when the project was completed or the main project date', null=True),
        ),
    ]
