# Generated by Django 5.2.1 on 2025-09-12 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zero', '0011_project_project_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-project_date'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_at',
        ),
    ]
